### ISSUE TITLE
[FEAT] create model APIs for admin

### ISSUE THREAD

**Issue by racheliee** [racheliee/kisia-project#18]
# Create db-overview APIs for admin

## todos
- [x] change database to new ERD
- [x] connect flask to PostgreSQL database
- [x] save URLs according to the new ERD
- [ ] update confusion matrix for each model with each query
- [ ] update confidence hit rate table with each query

## APIs to implement
- [ ] `/admin/model/confusion-matrix`
- [ ] `/admin/model/confidence-hit-rate`
